
logging_level: INFO

test_run: false

refresh_data: true
learning: true
forecast_future: true

input:
  model_pdq: None

pkl_path: './../data/pkl'

output:
  plot_dir: '../plots/'
  reports: '../reports'
  log_dir: '../reports'

start_date: '2024-01-03'
end_date: '2024-12-13'

trader_name: 'socrates'

indx_tckr: '^GSPC'

npredict: 12
ntrain: 180

ls_tckr:
  - '^GSPC'
  - 'ESG'
  - 'MSFT'
  - 'AAPL'
  - 'GE'
  - 'NVDA'
  - 'MMM'
  - 'AOS'
  - 'ABT'
  - 'ABBV'
#  - 'ACN'
#  - 'ADM'
#  - 'ADBE'
#  - 'ADP'
#  - 'AAP'
#  - 'AES'
#  - 'AFL'
#  - 'A'
#  - 'APD'
#  - 'AKAM'
#  - 'ALK'
#  - 'ALB'
#  - 'ARE'
#  - 'ALGN'
#  - 'ALLE'
#  - 'LNT'
#  - 'ALL'
#  - 'GOOGL'
#  - 'GOOG'
#  - 'MO'
#  - 'AMZN'
#  - 'AMCR'
#  - 'AMD'
#  - 'AEE'
#  - 'AAL'
#  - 'AEP'
#  - 'AXP'
#  - 'AIG'
#  - 'AMT'
#  - 'AWK'
#  - 'AMP'
#  - 'AME'
#  - 'AMGN'
#  - 'APH'
#  - 'ADI'
#  - 'ANSS'
#  - 'AON'
#  - 'APA'
#  - 'AAPL'
#  - 'AMAT'
#  - 'APTV'
#  - 'ACGL'
#  - 'ANET'
#  - 'AJG'
#  - 'AIZ'
#  - 'T'
#  - 'ATO'
#  - 'ADSK'
#  - 'AZO'
#  - 'AVB'
#  - 'AVY'
#  - 'BKR'
#  - 'BALL'
#  - 'BAC'
#  - 'BBWI'
#  - 'BAX'
#  - 'BDX'
#  - 'WRB'
#  - 'BBY'
#  - 'BIO'
#  - 'TECH'
#  - 'BIIB'
#  - 'BLK'
#  - 'BK'

